apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alpaca-prod
    ver: "1"
    env: prod
  name: alpaca-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alpaca-prod
      ver: "1"
      env: prod
  template:
    metadata:
      labels:
        app: alpaca-prod
        ver: "1"
        env: prod
    spec:
      containers:
      - image: gcr.io/kuar-demo/kuard-amd64:blue
        name: kuard-amd64
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          periodSeconds: 2
          initialDelaySeconds: 0
          failureThreshold: 3
          successThreshold: 1
